In [1136]:
import numpy as np
import random

x = 3
y = 3
numero_pecas = x * y

jogo = []
Movimentos = []
for i in range(numero_pecas):
    jogo.append(i)

In [1137]:
# criando tabuleiro

random.shuffle(jogo)
#Tabuleiro = np.reshape(jogo, (x, y)) 
#Tabuleiro

Movimentos.append(jogo)


In [1138]:
Movimentos

[[2, 8, 0, 7, 3, 5, 6, 1, 4]]

In [1139]:
resultado = np.array([[0,1],[2,3],[4,5]])
resultado

array([[0, 1],
       [2, 3],
       [4, 5]])

In [1140]:
jogo

[2, 8, 0, 7, 3, 5, 6, 1, 4]

In [1141]:
resultado = [1,2,3,4,0,5,6,7,8]
valores = [["comeco"]]
checagem = 0
for i in Movimentos:
    Index_Atual = Movimentos.index(i)
    local_0 = i.index(0)

    # 0 sobe
    if local_0 - y >= y:
        c = i.copy()
        c[local_0] = c[local_0-y]
        c[local_0-y] = 0
    
        if c not in Movimentos:
            Movimentos.append(c)
            aux = valores[Index_Atual].copy()
            aux.append("sobe")
            valores.append(aux)

            if c == resultado:
                break

    # 0 desce
    if local_0 + y < (x*y):
        c = i.copy()
        c[local_0] = c[local_0+y]
        c[local_0+y] = 0

        if c not in Movimentos:
            Movimentos.append(c)
            aux = valores[Index_Atual].copy()
            aux.append("desce")
            valores.append(aux)

            if c == resultado:
                break

    # 0 direita


    if (local_0) % y != 0:
        c = i.copy()
        c[local_0] = c[local_0-1]
        c[local_0-1] = 0

        if c not in Movimentos:
            Movimentos.append(c)
            aux = valores[Index_Atual].copy()
            aux.append("direita")
            valores.append(aux)
            if c == resultado:
                break
        
    # 0 esqueda
    if (local_0+1) % x != 0:
        c = i.copy()
        c[local_0] = c[local_0+1]
        c[local_0+1] = 0

        if c not in Movimentos:
            Movimentos.append(c)
            aux = valores[Index_Atual].copy()
            aux.append("esqueda")
            valores.append(aux)
            if c == resultado:

                break
        
        

In [1142]:
Tabuleiro = np.reshape(jogo, (x, y)) 
Tabuleiro

array([[2, 8, 0],
       [7, 3, 5],
       [6, 1, 4]])

In [1143]:
Tabuleiro = np.reshape(Movimentos[-1], (x, y)) 
Tabuleiro

array([[7, 2, 8],
       [6, 1, 4],
       [0, 3, 5]])

In [1144]:
[7, 1, 6, 3, 4, 5, 8, 2, 0] in Movimentos

False

In [1145]:
len(valores)

#realiza no maximo 360 movimentos ou 1083

1083